os: linux
language: node_js
node_js:
  - "node"
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi
  - npm install
script:
  - npm test
before_deploy:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -vE '\r|\n' | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "npm run pack"
    fi
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    file:
      - "dist/osx/VoTT-darwin-x64.zip"
      - "dist/win/VoTT-win32-x64.zip"
      - "dist/linux/VoTT-linux-x64.zip"
    on:
      tags: true