trigger: 
  none # disable CI build for branch
pr:
  - v2 # only kick off for pr targeting v2

jobs:
- job: Linux
  pool:
    name: Hosted Ubuntu 1604
  timeoutInMinutes: 60 # how long to run the job before automatically cancelling
  steps:
  - template: build/azure-pipelines/linux/continuous-build-linux.yml
