trigger: 
  - v2 # disable CI build for branch except v2
pr:
  - v2 # only kick off for pr targeting v2

jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 60 # how long to run the job before automatically cancelling
  steps:
  - checkout: self # self represents the repo where the initial Pipelines YAML file was found
    fetchDepth: 1  # the depth of commits to ask Git to fetch
  - template: azure-pipelines/linux/continuous-build-linux.yml
