jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 60 # how long to run the job before automatically cancelling
  steps:
  - checkout: self
    fetchDepth: 1

  - script: |
      set -e 
      sudo apt-get update
      sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 libgconf-2-4 dbus xvfb libgtk-3-0
      sudo cp build/azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
      sudo chmod +x /etc/init.d/xvfb
      sudo update-rc.d xvfb defaults
      sudo service xvfb start
    displayName: 'Install dependencies'

  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      set -e
      export DISPLAY=:99.0
      npm install
      npm run compile
      CI=true npm test # don't watch and just run all the tests
    displayName: 'Run tests'
