trigger:
  - v2 # disable CI build for branch except v2
pr: none # disable CI build for PR

jobs:
- job: Generate and Publish complexity report
  condition: succeeded()
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 60 # how long to run the job before automatically cancelling
  steps:
  - checkout: self # self represents the repo where the initial Pipelines YAML file was found
    fetchDepth: 1  # the depth of commits to ask Git to fetch
  - bash: |
    set -e

    COMMIT_SHA=`echo ${BUILD_SOURCEVERSION} | cut -c1-8`
    echo "sha: " $COMMIT_SHA

    # rewrite build number
    echo "##vso[build.updatebuildnumber]Report-${COMMIT_SHA}-${BUILD_BUILDNUMBER}"
    displayName: 'Rewrite Build number'

  - task: NodeTool@0
    displayName: 'Use Node 10.x'
    inputs:
        versionSpec: 10.x

  - bash: |
    set -e

    npm ci
    ./scripts/generate-report.sh

    displayName: 'Generate report'

  - task: AzureCLI@1
    displayName: 'upload report'
    inputs:
        azureSubscription: 'PELITTLE TEAM - CSE DWR (d36d0808-a967-4f73-9fdc-32ea232fc81d)'
        scriptPath: 'scripts/push-report.sh'

  - bash: |
    set -e

    COMMIT_SHA=`echo ${BUILD_SOURCEVERSION} | cut -c1-8`

    # clean up old resources
    rm -rf /tmp/drop && mkdir -p /tmp/drop

    # copy plato report to publish as artifacts
    cp -R report /tmp/drop/plato-report-${COMMIT_SHA}
    displayName: 'create artifact'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
        PathtoPublish: /tmp/drop
